[toolchain]
anchor_version = "0.28.0"
solana_version = "1.16.25"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
time_weighted_staking = "35C2x1zY4b1z5Gv2RhTf1rG3jc7UKzbjgSgv6Ww8ixeJ"

[programs.devnet]
time_weighted_staking = "35C2x1zY4b1z5Gv2RhTf1rG3jc7UKzbjgSgv6Ww8ixeJ"

[programs.mainnet]
time_weighted_staking = "35C2x1zY4b1z5Gv2RhTf1rG3jc7UKzbjgSgv6Ww8ixeJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "dev-authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "35C2x1zY4b1z5Gv2RhTf1rG3jc7UKzbjgSgv6Ww8ixeJ"
program = "target/deploy/time_weighted_staking.so"

[test.validator]
bind_address = "0.0.0.0"
url = "http://127.0.0.1:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899
gossip_port = 8001
dynamic_port_range = "8002-8020"

[workspace]
members = [
    "programs/time-weighted-staking"
]

[build]
exclude = ["node_modules"] 