// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahviquwdicsyqgsfnmfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFodmlxdXdkaWNzeXFnc2ZubWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTk3OTMsImV4cCI6MjA2MzY5NTc5M30.MRttR3G2FtRA5cZREEZ3LBkBCrPhA6GGAZa8wM4XFmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);